### ISSUE TITLE
作者可否出一下，怎么把latex转成word，查重需要word

### ISSUE THREAD

**Issue by Maplessw** [shinyypig/HFUT-Thesis#1]
作者可否出一下，怎么把latex转成word，查重需要word

**Comment by shinyypig** [comment]
不好转word，很麻烦，效果也不好。查重的话，可以直接把 LaTeX 代码粘贴进 word，我当年就是这么干的。

**Comment by shinyypig** [comment]
经咨询，可提交PDF进行查重。

**Comment by Maplessw** [comment]
十分感谢老师的帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shinyypig/HFUT-Thesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月26日(星期五) 晚上7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shinyypig/HFUT-Thesis] 作者可否出一下，怎么把latex转成word，查重需要word (Issue #1)





 
经咨询，可提交PDF进行查重。
