### ISSUE TITLE
你好，请问是根据最新的2024规范写的模板吗

### ISSUE THREAD

**Issue by forchannot** [shinyypig/HFUT-Thesis#2]
![image](https://github.com/shinyypig/HFUT-Thesis/assets/100580891/a4c995fd-d16d-4fac-a8a8-c9dd4ad70722)
![image](https://github.com/shinyypig/HFUT-Thesis/assets/100580891/386bd555-06d5-40cc-9d1f-38551fc58d49)

此外想请问下，正文中如何分别给中文和数字英文设置不同字体

**Comment by shinyypig** [comment]
已根据24年的模版修正过了，但难免会有疏漏（不过估计很难看出来了）。

中英文还有数字的字体都已经设置过了，符合要求。

**Comment by forchannot** [comment]
我看渲染出来的逗号是这样的
![image](https://github.com/shinyypig/HFUT-Thesis/assets/100580891/0e223f54-54f4-41ae-a771-f1fa1d3f09aa)
似乎和word里面的宋体有些许差异

**Comment by shinyypig** [comment]
问题不大，如果你想要更接近word的效果，根据pdf的教程，将字体替换为Adobe字体即可。

<img width="621" alt="image" src="https://github.com/shinyypig/HFUT-Thesis/assets/30233673/576a2b7d-dff3-4c82-9182-80d8165b2667">

效果如下：

<img width="121" alt="image" src="https://github.com/shinyypig/HFUT-Thesis/assets/30233673/fdb2f89a-f897-4178-9fac-6bb81a4c829e">

**Comment by forchannot** [comment]
![image](https://github.com/shinyypig/HFUT-Thesis/assets/100580891/ceffbb63-7908-4da6-9a15-f36dff93311b)
新版里面要求前置部分不要页码，如何删除呢，我试了`\thispagestyle{empty}`，但是仍然会有数字页码

**Comment by forchannot** [comment]
还有就是参考文献，要求里面是
![image](https://github.com/shinyypig/HFUT-Thesis/assets/100580891/7bf06f8c-25d7-472f-ad70-bb3167867924)
这样展示，但是实际的序号是右对齐
![image](https://github.com/shinyypig/HFUT-Thesis/assets/100580891/cbf876f1-ef5a-41d3-bc2d-410507614a20)

**Comment by shinyypig** [comment]
> ![image](https://github.com/shinyypig/HFUT-Thesis/assets/100580891/ceffbb63-7908-4da6-9a15-f36dff93311b)
> 
> 新版里面要求前置部分不要页码，如何删除呢，我试了`\thispagestyle{empty}`，但是仍然会有数字页码

前置部分不是要求用罗马数字吗？

**Comment by shinyypig** [comment]
> 还有就是参考文献，要求里面是
> 
> ![image](https://github.com/shinyypig/HFUT-Thesis/assets/100580891/7bf06f8c-25d7-472f-ad70-bb3167867924)
> 
> 这样展示，但是实际的序号是右对齐
> 
> ![image](https://github.com/shinyypig/HFUT-Thesis/assets/100580891/cbf876f1-ef5a-41d3-bc2d-410507614a20)
> 
> 

以LaTeX为准

**Comment by forchannot** [comment]
> 以LaTeX为准

我看目前我看到的参考文献都是标号左对齐，学校给的范例也都是左对齐的，要改的话怎么改呢，我在网上搜了搜默认就是左对齐，但不知道为什么生成出来是右对齐的

**Comment by forchannot** [comment]
> 前置部分不是要求用罗马数字吗？

这个我在咨询老师了

**Comment by shinyypig** [comment]
> > 前置部分不是要求用罗马数字吗？
> 
> 
> 
> 这个我在咨询老师了
> 
> 

我也是老师，本科生论文基本上只看格式是否统一。也就说，除去基本的字体字号之外，一切都可以以LaTeX为准。不用过于纠结word和LaTeX之间显示效果上的细微差异。

**Comment by forchannot** [comment]
谢谢您，不过我刚去源仓库https://github.com/hushidong/biblatex-gb7714-2015 查询了下，发现设置`gbalign=left`即可完全标号左对齐

**Comment by shinyypig** [comment]
> 谢谢您，不过我刚去源仓库https://github.com/hushidong/biblatex-gb7714-2015 查询了下，发现设置`gbalign=left`即可完全标号左对齐

方便的话，可以发起pull request，帮我更新一下模版。
